In [5]:
import numpy as np
import torch

In [12]:
x = np.array([[1,2],[3,4]])
x

array([[1., 2.],
       [3., 4.]])

In [13]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [14]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [16]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])