In [54]:
import torch

In [55]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5.,requires_grad=True)

In [56]:
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [57]:
y = w * x + b

In [58]:
print(y)

tensor(17., grad_fn=<AddBackward0>)


### in pytorch we can create the derivate of y automatically , this is called autograd

derivative of y with w <br>
dy/dw = d(wx)/d(w) + d(b)/d(w) <br>
derivate of constants are zero <br>

dy/dw = d(wx)/d(w) <br>
x is a constant <br>
dy/dw = x * d(w)/d(w) <br>
dy/dw = x <br>


dy/dx d(wx)/d(x) <br>



In [59]:
dy = y.backward()

### it will create the derivate of y with each inputs
1. it will create dy/dx
2. it will create dy/dw
3. it will create dy/db



In [60]:
print(x.grad)
print(w.grad)
print(b.grad)


None
tensor(3.)
tensor(1.)


We havnt define the requires_grad to true for x , thats why its none. 












<h1> Tensor Functions 

In [63]:
tfull = torch.full((3,2) , 42)

In [64]:
tfull

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [66]:
tnew = torch.full((3,2) , 21.)

In [67]:
tnew

tensor([[21., 21.],
        [21., 21.],
        [21., 21.]])

In [74]:
t7 = torch.cat((tnew,tfull))
print(t7)

tensor([[21., 21.],
        [21., 21.],
        [21., 21.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])


In [81]:
t8 = torch.sin(t7)
print(t8)

tensor([[ 0.8367,  0.8367],
        [ 0.8367,  0.8367],
        [ 0.8367,  0.8367],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])


In [82]:
t7.shape

torch.Size([6, 2])

In [86]:
t9 = t8.reshape(2,6)
print(t9)
print(t9.shape)
t9_1 = t8.reshape(2,3,2)
print(t9_1)
print(t9_1.shape)

tensor([[ 0.8367,  0.8367,  0.8367,  0.8367,  0.8367,  0.8367],
        [-0.9165, -0.9165, -0.9165, -0.9165, -0.9165, -0.9165]])
torch.Size([2, 6])
tensor([[[ 0.8367,  0.8367],
         [ 0.8367,  0.8367],
         [ 0.8367,  0.8367]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165],
         [-0.9165, -0.9165]]])
torch.Size([2, 3, 2])
